# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.1'
info:
  title: 'moviebattle'
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Development server
  - url: https://localhost:8080/api
    description: Development server with TLS Profile
paths:
  /startGame:
    get:
      summary: returns an id value which can be used as gameSessionId parameter in other endpoints
      operationId: startGame
      responses:
        '200':
          description: use the returned id value in other endpoints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameSessionDTO'
        '400':
          description: could not generate a new gameSessionId
      security:
        - sessionId: []
  /nextRound:
    get:
      summary: returns the next open
      operationId: nextRound
      parameters:
        - name: gameSessionId
          in: query
          description: a previously created gameSessionId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: use the returned id value as GameRoundId in other endpoints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnansweredGameRoundDTO'
        '404':
          description: invalid gameSession ID supplied
        '422':
          description: gameSession has already ended
        '500':
          description: inconsitent game stateñ
      security:
        - sessionId: []
components:
  schemas:
    GameSessionDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
    UnansweredGameRoundDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        left:
          type: string
          example: Star Wars
        right:
          type: string
          example: Star Trek

  responses:
    Problem:
      description: error occurred - see status code and problem object for more information.
      content:
        'application/problem+json':
          schema:
            $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'

  securitySchemes:
    sessionId:
      type: apiKey
      name: JSESSIONID
      in: cookie
    csrf:
      type: apiKey
      name: XSRF-TOKEN
      in: cookie
security:
  - sessionId: []
  - csrf: []
