# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.1'
info:
  title: 'moviebattle'
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Development server
  - url: https://localhost:8080/api
    description: Development server with TLS Profile
paths:
  /startGame:
    post:
      summary: returns a new gameSessionId value
      operationId: startGame
      responses:
        '200':
          description: use the returned gameSessionId in other endpoints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameSessionDTO'
        '400':
          description: could not generate a new gameSessionId
      security:
        - sessionId: []
  /stopGame/{gameSessionId}:
    post:
      summary: stops the game, no more rounds can be played with that gameSessionId
      operationId: stopGame
      parameters:
        - name: gameSessionId
          in: path
          description: the gameSessionId that identifies the current session
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: gameSessionId is ended
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameSessionDTO'
        '422':
          description: gameSession has already ended
      security:
        - sessionId: []
  /nextRound/{gameSessionId}:
    post:
      summary: returns the next open round (i.e. round where userChoice is NONE)
      operationId: nextRound
      parameters:
        - name: gameSessionId
          in: path
          description: the gameSessionId that identifies the current session
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: use the returned id value as gameRoundId in other endpoints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnansweredGameRoundDTO'
        '404':
          description: invalid gameSession ID supplied
        '422':
          description: gameSession has already ended
        '500':
          description: inconsistent game state
      security:
        - sessionId: []
  /answerRound/{gameRoundId}:
    post:
      summary: answers the the round identified by gameRoundId
      operationId: answerRound
      parameters:
        - name: gameRoundId
          in: path
          description: the gameRoundId that identifies the current round
          required: true
          schema:
            type: integer
        - name: userChoice
          in: query
          description: the user choice (whether he thinks LEFT movie has more ranking than RIGHT movie)
          required: true
          schema:
            type: string
            enum: [LEFT, RIGHT]
      responses:
        '200':
          description: the returned object indicates whether answer was correct or not
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnsweredGameRoundDTO'
        '404':
          description: invalid gameRound ID supplied
        '422':
          description: gameSession has already ended
        '500':
          description: inconsistent game state
      security:
        - sessionId: []
components:
  schemas:
    GameSessionDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        userId:
          type: string
          example: player1
        finished:
          type: boolean
          example: false
    UnansweredGameRoundDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        left:
          type: string
          example: Star Wars
        right:
          type: string
          example: Star Trek
    AnsweredGameRoundDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        left:
          type: string
          example: Star Wars
        right:
          type: string
          example: Star Trek
        userChoice:
          type: string
          example: LEFT
        correct:
          type: boolean
          example: false
  responses:
    Problem:
      description: error occurred - see status code and problem object for more information.
      content:
        'application/problem+json':
          schema:
            $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'

  securitySchemes:
    sessionId:
      type: apiKey
      name: JSESSIONID
      in: cookie
    csrf:
      type: apiKey
      name: XSRF-TOKEN
      in: cookie
security:
  - sessionId: []
  - csrf: []
